FROM openjdk:17
COPY target/currency-conversion-service-0.0.12-SNAPSHOT.jar currency-conversion-service-0.0.12-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/currency-conversion-service-0.0.12-SNAPSHOT.jar"]